### ISSUE TITLE
Wrong rotation values in TRLE animations

### ISSUE THREAD

**Issue by TokyoSU** [veeti512/wadblender#1]
Some lara obj and maybe entity have wrong value for animation in blender !
It's more obvious with weapon animation.
Wadmerger: https://i.imgur.com/MBSxoe5.png
Blender: https://i.imgur.com/WuSdqb6.png
PS: im using the latest commit instead of the release since it's old.

**Comment by TokyoSU** [comment]
It's not just feet, it include weapon and maybe many more object that use animation:
![pistol_blender](https://user-images.githubusercontent.com/77746747/107420310-0e1bf600-6b19-11eb-91ad-ff12836a106b.PNG)
![pistol_wadmerger](https://user-images.githubusercontent.com/77746747/107420314-0eb48c80-6b19-11eb-85d3-953e30321977.PNG)

**Comment by veeti512** [comment]
Ok, I see! I'll check into it, hope it is fixable!

**Comment by TokyoSU** [comment]
i hope too, it's a wonderful tool for extracting object with a rigging :)

**Comment by veeti512** [comment]
Fixed!

**Comment by TokyoSU** [comment]
No commit available for testing it myself :'( only readme.

**Comment by veeti512** [comment]
Ops, I forgot to push! Thanks!

**Comment by TokyoSU** [comment]
i will test it right away :)
