### ISSUE TITLE
Wrong joint when importing lara from TR4+

### ISSUE THREAD

**Issue by TokyoSU** [veeti512/wadblender#12]
The joint are not "joined" with the skin so it look wreid in blender and maybe unity too, ive not tested further since it not look good (and i planning to use TR3 lara instead) but for some that need TR4/TR5 lara with skin and skin joint then its a problem :x
PS: when lara is animated the joint are distorded (vertex)

**Comment by veeti512** [comment]
Did you try with the default TR4 Lara or with custom outfits?

**Comment by TokyoSU** [comment]
default or custom cause it, the joint are just not joined with the skin and cause vertex bug when animating

**Comment by veeti512** [comment]
Custom Lara outfits need to have vertices remapped manually. Each skin joint is connected to the actual body parts via vertex groups, so one needs to alter them to point to the correct vertices. I will eventually implement auto-mapping.

**Comment by veeti512** [comment]
In the last commit Lara skin joints are mapped automatically. If some custom outfits do not work properly please let me know, some parameters may need to be tuned 👍
