### ISSUE TITLE
Animation name is wrong if we import TR3 lara with TR4 slot name

### ISSUE THREAD

**Issue by TokyoSU** [veeti512/wadblender#13]
Just a suggestion but can you separate slot name and animation name ?
If i import the lara from TR3 the slot name are the same as TR4 but i want the TR3 name instead, if you have time can you add this feature ?

**Comment by veeti512** [comment]
When you have time, can you please make a simple example? I see the correct TR3 object names and animation names

**Comment by TokyoSU** [comment]
Im using TR4 Name slot when importing lara, so obviously the name will be TR4 not TR3, if possible can you separate object name and animation name for lara ?

**Comment by veeti512** [comment]
I hope I understood correctly, I added the option in advanced! Let me know when you try it!

**Comment by TokyoSU** [comment]
sorry for the time, i tested it with TR3 lara, the name same fine :)

**Comment by TokyoSU** [comment]
since it's fixed, i will close it.
