### ISSUE TITLE
Need to flip the face manually

### ISSUE THREAD

**Issue by TokyoSU** [veeti512/wadblender#16]
The model have the wrong face flipping, in unity the texture are in the interior, you need to flip it manually in blender.
If you can add a checkbox to flip it in the script would be great.

PS: recalculating the face outside at the end would be great too :)

**Comment by veeti512** [comment]
I will reintroduce the option, I think that TRLE positive normals directions are the same as unity but opposite to blender :/

**Comment by veeti512** [comment]
I reintroduced the option, hope it doesn't break anything else
