### ISSUE TITLE
Error messages when importing stock wad

### ISSUE THREAD

**Issue by LoreRaider** [veeti512/wadblender#18]
I'm getting some errors while importing a stock wad in blender using the latest released version

Repro steps:
-go to File->Import->Tomb Raider 4 WAD file (.wad) 
-set the following options: 
![image](https://user-images.githubusercontent.com/48493527/126649056-ed8fd9b6-a689-4392-83ea-f9cb9d452c27.png)
-select the wad and press Import WAD

Error:
![image](https://user-images.githubusercontent.com/48493527/126649020-bcce20b6-2499-4595-ad20-9fbaea2f1609.png)

Here's the wad I'm trying to import 
[catacombWad.zip](https://github.com/veeti512/wadblender/files/6862638/catacombWad.zip)

**Comment by veeti512** [comment]
I think that you're using an old version. Can you please try downloading the addon from the green code button in the homepage then "download zip".

**Comment by LoreRaider** [comment]
Does it work the same way? I see that the files are differently placed than the release packages

**Comment by veeti512** [comment]
It should be fixed now!
Be aware that if you do Choose Object -> LARA, Blender will load Lara as she is stored in the wad, i.e. with placeholder meshes. Uncheck LARA to have those replaced with the right meshes.

**Comment by LoreRaider** [comment]
Yeah it indeed works now, thanks!

Now I tried to load up a very heavy wad and it throws an error about VEHICLE_EXTRA key not found
Error: 
![image](https://user-images.githubusercontent.com/48493527/126863894-56747c9a-e0f5-4383-a7e6-5241f40f533d.png)

If you want to try the wad yourself: 
[persia.zip](https://github.com/veeti512/wadblender/files/6872151/persia.zip)

**Comment by veeti512** [comment]
Thanks, fixed also another issue with that wad. It was an object naming issue. Testing now, my pc is frying :D
Be aware that mapping of joints is not implemented for custom Lara outfits, please see #12

**Comment by LoreRaider** [comment]
Yeah I've seen that, though using TR4 lara it's perfect anyway for stuff like animating for now :D
Also yes my PC was frying too while loading this big wad lol

This time I've got an error related to statics using the same wad, maybe something about too many vertices?
![image](https://user-images.githubusercontent.com/48493527/126873659-fb6912ed-2911-47b0-91b1-cf2332b5731c.png)

**Comment by veeti512** [comment]
Sorry, I missed that. The error is strange because it is not able to load the lighting info for that nice plant EXTRA40. WAD tool says that the light for that object is dynamic. It must be some new staff. I think I can get a workaround real quick.

**Comment by LoreRaider** [comment]
Oh yes I see now, apparently they forgot to put static lighting back when importing the object into the wad
And yes, statics can be set to have dynamic lighting, as well as moveables being set to have static lighting

**Comment by veeti512** [comment]
It should be able to load the entire wad now. Probably there will be errors when importing movables with static lights. I need to find docs for that to see how's it stored.

**Comment by LoreRaider** [comment]
Just checked and it's indeed good now, I also tested with another big wad and it loaded everything fine, thank you for this!

**Comment by veeti512** [comment]
you're very welcome. Please let me know if you find other issues!
