### ISSUE TITLE
Wrong Animation Name

### ISSUE THREAD

**Issue by TokyoSU** [veeti512/wadblender#2]
It's not really important but the animation name is the obj name + _RIG with animation id in CapLock, but if you could use the animations_name.txt instead, it would be more structured :)
https://i.imgur.com/pxoG0AJ.png

**Comment by veeti512** [comment]
Good point, I want to ask first the author of Tomb Editor if I can use his animation/object names.

**Comment by veeti512** [comment]
Now WADBlender uses the same names as Tomb Editor.
