### ISSUE TITLE
Too much material in blender

### ISSUE THREAD

**Issue by TokyoSU** [veeti512/wadblender#3]
The name resume the problem: https://i.imgur.com/CfQtrJg.png
it's probably for compatibility but you can add a option to regroup it to only one ?

**Comment by veeti512** [comment]
It is for dealing with shine and transparency for movables. I can add an option to discard them so that a single material is instantiated, but I'm not aware of a method to regroup those properties into a single material.

**Comment by TokyoSU** [comment]
it's not really a problem since we can just discard it manually and assign a single material to the lara object,
if you can add a option, it would just speed up the process :x

**Comment by veeti512** [comment]
Option added on last commit!

**Comment by veeti512** [comment]
Found a way to import shine and opacity with only one material (vertex color).  Also imported opacity was wrong. Fixing it later.. Ill keep the 64 materials as an option for wad tool compatibility

**Comment by TokyoSU** [comment]
oh nice found :D it will be more complete that way (but it's already good lol) :)
