### ISSUE TITLE
Double animation when extracting to fbx

### ISSUE THREAD

**Issue by TokyoSU** [veeti512/wadblender#4]
When extracting to .fbx, the animation is doubled, i have the LARA_RIGXXX and also LARA_RIG|LARA_RIGXXX animation.
because of this my fbx file go to 50mb O.O but in blender i only have LARA_RIGXXX Action Anim.
The more lara have animation, the more the mb will increase, but it's caused by blender for keyframe etc.. so it's not fixable.

**Comment by veeti512** [comment]
Are you using the batch exporter in the tool or the blender export fbx?

**Comment by TokyoSU** [comment]
the blender export

**Comment by TokyoSU** [comment]
i can comfirm that the batch exporter or blender do the same but i can see the action anim in blender with the batch from the import: 
![doubleanimation](https://user-images.githubusercontent.com/77746747/107529980-b5516980-6bbb-11eb-961c-f6bf85b68d6f.PNG)
also the batch exporter create a second rig without mesh that are unused :x

**Comment by veeti512** [comment]
mmmh, I cannot replicate. Maybe you imported everything and unchecked the option discard placeholders? The placeholders include LARA animations with the thigh meshes, so that may be the reason of having them doubled

**Comment by TokyoSU** [comment]
It's checked, maybe it's my blender that cause that, i have the latest version.

**Comment by TokyoSU** [comment]
It's wreid, the step i do:
- Import the wad like normal without batch with placeholders checked.
- Delete the action anim (312 in total since i use the Lara from TR3)
- Export it via blender fbx without changing anything. normally there are only the mesh since the animation not exist anymore but there why does the animation are exported when importing the fbx back to blender:
![wreidbehaviour](https://user-images.githubusercontent.com/77746747/107535828-67d7fb00-6bc1-11eb-97da-e711df58065b.PNG)

**Comment by TokyoSU** [comment]
i dont know if it's your tool or blender and it's irritating since the release 0.3b worked perfectly except the rotation problem.

**Comment by TokyoSU** [comment]
Confirmed, your release 0.3b work fine, it's not blender.

**Comment by veeti512** [comment]
Did you also delete the NLA tracks in the non linear animations panel?

**Comment by TokyoSU** [comment]
... no :x

**Comment by veeti512** [comment]
Maybe when you export you can leave checked all actions and uncheck the nla strip option in the export fbx menu. NLA strips may cause troubles when importing into unity. If it doesn't solve your problem I can add an option to avoid generating nla strips (I removed it to keep the interface simple but I can put it back)

**Comment by TokyoSU** [comment]
Fixed with the nla strip off.

**Comment by veeti512** [comment]
Oh I don't know. I suppose that the FBX exporter does not care that the NLA strip and actions are the same and export both as animations. Looking better at the first screenshot you posted I see LARA_RIG.001, this happens when you import two times LARA. In the second there is CAMERA.001, I don't know what it is. Maybe something is misplaced in the wad? or you imported something before and got name conflicts.  It is always better to create a new blend file when importing, otherwise shit happens :/

**Comment by TokyoSU** [comment]
maybe importing LARA and LARA_RIG cause that ?
but i dont know why the CAMERA and LIGHT was there  in the animation xD

**Comment by TokyoSU** [comment]
Since a warning are in the readme, you can close this issue.
