### ISSUE TITLE
Inverted Face

### ISSUE THREAD

**Issue by TokyoSU** [veeti512/wadblender#5]
Don't know if it's me or your tool but i get this when extracting to .fbx:
https://i.imgur.com/C3h28gC.png
it was not like that before like using the release, this not happened :x

**Comment by veeti512** [comment]
Is that screenshot from Blender?

**Comment by TokyoSU** [comment]
No from Open3Mod since blender draw it correctly :x but one this or Unity it's not correctly drawed.

**Comment by veeti512** [comment]
That's because Blender has not backface culling enabled by default. I kept the normals as TRLE, but it is better if I revert back to flipping them. I will add an option later.

**Comment by TokyoSU** [comment]
thanks, it will help :)

**Comment by veeti512** [comment]
Option added on last commit!
