### ISSUE TITLE
Import wad fail

### ISSUE THREAD

**Issue by TokyoSU** [veeti512/wadblender#6]
If i try to import a wad with the master version, i get this error:
![importwaderror](https://user-images.githubusercontent.com/77746747/107620399-e92c9d80-6c54-11eb-87d9-5abf054167fd.PNG)

**Comment by TokyoSU** [comment]
it's caused by the Discard shine and transparent option

**Comment by veeti512** [comment]
I think it is a cache problem. Sorry about that, please try this:
close Blender and go to blender addons folder with your file explorer, something like C:\blender-2.90.1-windows64\2.90\scripts\addons\wadblender. Delete the __pycache__ folder, reopen Blender and try again.

**Comment by TokyoSU** [comment]
Fixed :)
You can add a warning in the readme about the cache when updating (if it's not already added obviously :x )
