### ISSUE TITLE
No animation for some objects

### ISSUE THREAD

**Issue by TokyoSU** [veeti512/wadblender#7]
You maybe know about it but some weapon like TR3 weapon inventory with only one mesh are not animated in blender since no armature is extracted :x

**Comment by veeti512** [comment]
Thanks, I forgot about them!

**Comment by veeti512** [comment]
It should be fixed now!

**Comment by TokyoSU** [comment]
I tested it with the shotgun (and latest version in the git), work like a charm :D nice work :)
