### ISSUE TITLE
Possibility to import WAD2 (or Single Texture Export when importing) ?

### ISSUE THREAD

**Issue by TokyoSU** [veeti512/wadblender#8]
Im having some problem with wadmerger beta3 (ngle update) since some object wont export (subscribe out of range "classic error"), do you have planned to do the wad2 import too ?
additionnaly when importing a single object from a full wad, the full wad texture will be extracted, i just want to extract a single texture instead :x can it be extracted to a single texture or it's not possible ?

**Comment by veeti512** [comment]
By single texture you mean a texture page 256x256? If so, next update I will add an option to create one material for each page. Then, when you export, the unused texture pages should be discarded. 

I dont know about the wad2, by the way, they added in wad tool the possibility to export meshes. I think it will also remove the inused textures. Did you try?

**Comment by TokyoSU** [comment]
- if it create a texture page for each objects and export the only one necessary then i and the community will gladly accept this feature :D
- It export the mesh but also the animation and create a rig ? if so i could test it if it's compatible with Unity/Unreal.

**Comment by veeti512** [comment]
I see, I like this feature! First I need to finish another feature, then I'll see what I can do. In the meantime I think you can do it by yourself, see this https://blender.stackexchange.com/questions/15510/possible-to-bake-texture-to-new-uv-map

**Comment by veeti512** [comment]
unfortunately, the method in the link I posted fails too many times. I managed to do something like this instead, is that what you asked? The object texture map is at the left 
![2021-03-02](https://user-images.githubusercontent.com/11755584/109616233-38b80800-7b35-11eb-8cbf-d66234819195.png)

**Comment by TokyoSU** [comment]
Sorry for the wait, it look perfect :) i will see it myself and report it if it's what im looking for.
